apiVersion: v2
name: my-magda-app
description: A Helm chart for Kubernetes
version: "2.0.0"
kubeVersion: ">= 1.16.0-0"
dependencies:
  - name: magda
    version: "2.2.0"
    repository: "oci://ghcr.io/magda-io/charts"

  - name: magda-auth-internal
    version: "2.0.0"
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - all
      - magda-auth-internal

  - name: magda-ckan-connector
    version: "2.0.0"
    alias: connector-dga
    repository: "oci://ghcr.io/magda-io/charts"
    tags:
      - connectors
      - connector-dga